//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SilverLightWithWcfTest.StockServiceRef {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockPriceContract", Namespace="http://schemas.datacontract.org/2004/07/StockServiceLibrary")]
    public partial class StockPriceContract : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> ClosePriceField;
        
        private System.Nullable<decimal> LastTradedPriceField;
        
        private string NameField;
        
        private System.Nullable<decimal> OpenPriceField;
        
        private string SymbolField;
        
        private System.Nullable<decimal> TradedVolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ClosePrice {
            get {
                return this.ClosePriceField;
            }
            set {
                if ((this.ClosePriceField.Equals(value) != true)) {
                    this.ClosePriceField = value;
                    this.RaisePropertyChanged("ClosePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LastTradedPrice {
            get {
                return this.LastTradedPriceField;
            }
            set {
                if ((this.LastTradedPriceField.Equals(value) != true)) {
                    this.LastTradedPriceField = value;
                    this.RaisePropertyChanged("LastTradedPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OpenPrice {
            get {
                return this.OpenPriceField;
            }
            set {
                if ((this.OpenPriceField.Equals(value) != true)) {
                    this.OpenPriceField = value;
                    this.RaisePropertyChanged("OpenPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TradedVolume {
            get {
                return this.TradedVolumeField;
            }
            set {
                if ((this.TradedVolumeField.Equals(value) != true)) {
                    this.TradedVolumeField = value;
                    this.RaisePropertyChanged("TradedVolume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockServiceRef.IStockService")]
    public interface IStockService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStockService/GetStockPrices", ReplyAction="http://tempuri.org/IStockService/GetStockPricesResponse")]
        System.IAsyncResult BeginGetStockPrices(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverLightWithWcfTest.StockServiceRef.StockPriceContract> EndGetStockPrices(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockServiceChannel : SilverLightWithWcfTest.StockServiceRef.IStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStockPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStockPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverLightWithWcfTest.StockServiceRef.StockPriceContract> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverLightWithWcfTest.StockServiceRef.StockPriceContract>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockServiceClient : System.ServiceModel.ClientBase<SilverLightWithWcfTest.StockServiceRef.IStockService>, SilverLightWithWcfTest.StockServiceRef.IStockService {
        
        private BeginOperationDelegate onBeginGetStockPricesDelegate;
        
        private EndOperationDelegate onEndGetStockPricesDelegate;
        
        private System.Threading.SendOrPostCallback onGetStockPricesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public StockServiceClient() {
        }
        
        public StockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetStockPricesCompletedEventArgs> GetStockPricesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverLightWithWcfTest.StockServiceRef.IStockService.BeginGetStockPrices(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStockPrices(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverLightWithWcfTest.StockServiceRef.StockPriceContract> SilverLightWithWcfTest.StockServiceRef.IStockService.EndGetStockPrices(System.IAsyncResult result) {
            return base.Channel.EndGetStockPrices(result);
        }
        
        private System.IAsyncResult OnBeginGetStockPrices(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverLightWithWcfTest.StockServiceRef.IStockService)(this)).BeginGetStockPrices(callback, asyncState);
        }
        
        private object[] OnEndGetStockPrices(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverLightWithWcfTest.StockServiceRef.StockPriceContract> retVal = ((SilverLightWithWcfTest.StockServiceRef.IStockService)(this)).EndGetStockPrices(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStockPricesCompleted(object state) {
            if ((this.GetStockPricesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStockPricesCompleted(this, new GetStockPricesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStockPricesAsync() {
            this.GetStockPricesAsync(null);
        }
        
        public void GetStockPricesAsync(object userState) {
            if ((this.onBeginGetStockPricesDelegate == null)) {
                this.onBeginGetStockPricesDelegate = new BeginOperationDelegate(this.OnBeginGetStockPrices);
            }
            if ((this.onEndGetStockPricesDelegate == null)) {
                this.onEndGetStockPricesDelegate = new EndOperationDelegate(this.OnEndGetStockPrices);
            }
            if ((this.onGetStockPricesCompletedDelegate == null)) {
                this.onGetStockPricesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStockPricesCompleted);
            }
            base.InvokeAsync(this.onBeginGetStockPricesDelegate, null, this.onEndGetStockPricesDelegate, this.onGetStockPricesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverLightWithWcfTest.StockServiceRef.IStockService CreateChannel() {
            return new StockServiceClientChannel(this);
        }
        
        private class StockServiceClientChannel : ChannelBase<SilverLightWithWcfTest.StockServiceRef.IStockService>, SilverLightWithWcfTest.StockServiceRef.IStockService {
            
            public StockServiceClientChannel(System.ServiceModel.ClientBase<SilverLightWithWcfTest.StockServiceRef.IStockService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetStockPrices(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetStockPrices", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverLightWithWcfTest.StockServiceRef.StockPriceContract> EndGetStockPrices(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverLightWithWcfTest.StockServiceRef.StockPriceContract> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverLightWithWcfTest.StockServiceRef.StockPriceContract>)(base.EndInvoke("GetStockPrices", _args, result)));
                return _result;
            }
        }
    }
}
